### PR TITLE
replace travis with github workflow for test CI

### PR DESCRIPTION
**Pull request by notEthan**

### CODE REVIEW

**Comment by notEthan** [comment]
I guess this PR doesn't trigger the PR action until it's merged on the default branch

**Comment by notEthan** [comment]
to check this is set up right, I reckon a maintainer could trigger the push action by pushing a branch on the main repository, though. something like:
git remote add notEthan https://github.com/notEthan/jsonpath.git
git fetch notEthan
git push origin notEthan/ci:refs/heads/ci

**Comment by joshbuddy** [comment]
Going to merge and get it working, thank yoU!

**Comment by joshbuddy** [comment]
This merged and tests ran successfully, so, looks good

**Pull request merged**
