### PR TITLE
Selecting multiple keys/values

### LINKED ISSUE #92: Selecting multiple keys/values
Hi @Skarlso not sure if this is a bug per se, but I can't seem to get this to work (even on jsonpath.com) but can on other evaluators.

JSON
```
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            }
        ]
}
```

JSONPath
```
$.store.book[*]['category', 'author']
```

Desired outcome
```
[
   {
      "category" : "reference",
      "author" : "Nigel Rees"
   },
   {
      "category" : "fiction",
      "author" : "Evelyn Waugh"
   }
]
```

### PR DESCRIPTION
**Pull request by Skarlso**
Finally got around to do this... Took a long time.

This is draft, I'll do some cleanup after. But this looks promising.

### CODE REVIEW

**Comment by Skarlso** [comment]
@NDuggan Hi! I know it has been a long long time, but would you mind giving this a try? 

The syntax is slightly different as the `[]` was problematic. You would provide this at the end of a query like this: `(category,title)` coma separated list inside parenthesis. Is that cool? Cheers.

**Comment by NDuggan** [comment]
Hi @Skarlso, nice work!

Just tested it and it worked as expected with the new syntax:
```rb
$.store.book[*](category,author)
```

One side note, it didn't work with a space between the attribute names - assuming this is a feature as opposed to a bug though, so might just be worth noting for the docs.
```rb
$.store.book[*](category, author)
```

**Comment by Skarlso** [comment]
@NDuggan Excellent! Thanks. Oh yeah I need a trim in there. :) 👍

**Comment by Skarlso** [comment]
@NDuggan Alright, this should now work while still allowing the json category to contain spaces. Although I doubt anyone would do something like that. :D You'd never know. :) Thank you for testing!

**Pull request merged**
