### PR TITLE
Support '@' and '$' as part of member names

### PR DESCRIPTION
**Pull request by pezra**
Allows using paths on documents that use sigils to namespace meta data
or common fields such as JSON-LD

### CODE REVIEW

**Comment by Skarlso** [comment]
I closed it because it should be fixed in 0.7.0. Could you test it please?

Cheers.

**Comment by pezra** [comment]
`@` was fixed but not `$`. i updated the code.

**Comment by Skarlso** [comment]
Huh, interesting. I really thought I already did this. Huh. I guess I lost in between commits. :/

Cheers man. :)

**Comment by pezra** [comment]
No worries. Super glad to see this gem getting a little attention.

**Comment by Skarlso** [comment]
Word. 👍 :)

**Comment by Skarlso** [comment]
I'm gonna cut a new version soon as well.

**Comment by pezra** [comment]
thanks

**Pull request merged**
