### PR TITLE
Support traversing ruby objects

### PR DESCRIPTION
**Pull request by doits**
based on top of #111

### CODE REVIEW

**Comment by doits** [comment]
This is simply an addition to traverse ruby objects. On a first glance it looks like there are only few changes needed to support it.

My use case is to run expression against Rails ActiveRecord models. I first tried to do it without this change by doing `model.to_json` first which worked with simple attributes (database columns). But if there was a method ...

```rb
class Model < ActiveRecord::Base
  def some_method
    'string'
  end
end
```

... then `.to_json` will not include the method, so I couldn't use `$.some_method` for example.

```rb
model = Model.new
JsonPath.new('$.some_method').on(model.to_json)
# => []
```

With these MR, by directly using the ruby object and sending keys to it, everything is accessible:

```rb
model = Model.new
JsonPath.new('$.some_method').on(model)
# => ['string']
```

**Comment by Skarlso** [comment]
Looks good after merge conflict has been resolved.

**Comment by doits** [comment]
rebased it on lates #111

**Comment by Skarlso** [comment]
I'll mule over this a bit. :D

**Comment by doits** [comment]
Take your time @Skarlso  :-) Rebased it again on master so this is now clear.

**Comment by Skarlso** [comment]
Thanks!! I'll do a release today. :)

**Pull request merged**
