### PR TITLE
[WIP] Add support for a :use_symbols option (when "json" data is ruby data)

### PR DESCRIPTION
**Pull request by blambeau**
Hey @joshbuddy,

I'd like to add JsonPath support to a couple of gems I maintain, e.g. [Bmg](https://github.com/enspirit/bmg), [Predicate](https://github.com/enspirit/predicate) and [Finitio](https://github.com/blambeau/finitio-rb).

Yet there all "data" is actually ruby data, that is with all keys symbolized...

Would you consider merging this PR if I add full support for that, as suggested in the first test?

Thanks, and Merry Christmas.

### CODE REVIEW

**Comment by blambeau** [comment]
@Skarlso

**Comment by Skarlso** [comment]
hey @blambeau 

LGTM, I'll take a look later on to see if it collides with anything. :)

**Comment by Skarlso** [comment]
@blambeau I took a closer look, this looks okay to me. I'll merge and make a release later on. :) Merry Christmas to you too! :)

**Comment by Skarlso** [comment]
@blambeau Is there is a reason why there is still `[WIP]` in the title? Are you planning on adding something more?

**Comment by blambeau** [comment]
@Skarlso yes, it does not work with filters so far. I plan to add that a little bit later.

**Comment by blambeau** [comment]
@Skarlso btw, I think the code could be improved to favor usage of the #dig protocol introduced in ruby 2.3, instead of hardcoding `is_a?(Hash)` and that kind of typed logic.

**Pull request closed without merging**
