### PR TITLE
Generate jsonpath list from json 

### PR DESCRIPTION
**Pull request by mohanapriya2308**
Fix for issue id : [#126](https://github.com/joshbuddy/jsonpath/issues/126)

### CODE REVIEW

**Comment by joshbuddy** [comment]
Hey @mohanapriya2308, this is a neat idea. Looking like the tests are failing however

**Comment by mohanapriya2308** [comment]
@joshbuddy 
All cases passed expect Jruby
Jruby issue: [#6581](https://github.com/jruby/jruby/issues/6581)

**Comment by joshbuddy** [comment]
@mohanapriya2308 It looks like we can work around this issue by adding `racc` to the dev dependencies. I'd say lets do that just so we can get this passing again

**Comment by mohanapriya2308** [comment]
Hi Joshua,
Sure. Let me know how to proceed, or if you need any help from my side.

Thanks,
Mohana

**Comment by joshbuddy** [comment]
You would need to add it to the dev dependencies on your branch, re bundle and push that commit

**Pull request merged**
